var URLS = {};

var HOST_ROOT = "http://127.0.0.1:9420/spgm"; // Development
//var HOST_ROOT = "http://125.228.20.167:3320/spgm"; // Test

var operationPath = {
	"GET": "/get/", 
	"LIST": "/list", 
	"QUERY": "/query",
	"SAVE": "/save",
	"CHECK": "/check",
	"COUNT": "/count",
	"DELETE": "/delete"
};

function buildCommonPath(rootPath) {
	var url = {};
	url.ROOT = URLS.ROOT + rootPath;
	for (var key in operationPath) {
	    if (operationPath.hasOwnProperty(key)) {
	 		url[key] = url.ROOT + operationPath[key];
		}
	}
	return url;
}

function setUrls() {
	
	URLS.CONTENT = {};
	if (APPLICATION.ENV.runningCordova) {
		URLS.ROOT = (APPLICATION.ENV.isNetworking() ? HOST_ROOT : "..");
		URLS.CONTENT.ROOT = '../..'; 
	}
	else {
		//URLS.ROOT = (APPLICATION.ENV.isNetworking() ? HOST_ROOT : "../..");
		URLS.ROOT = HOST_ROOT;
		URLS.CONTENT.ROOT = URLS.ROOT; 
	}
	
	URLS.SCRIPT = URLS.CONTENT.ROOT + '/script';

	URLS.CONTENT.HTML = URLS.CONTENT.ROOT + '/html';
	URLS.HOME = URLS.CONTENT.HTML + '/page/index.html';

	URLS.CONTENT.COMMOM = URLS.CONTENT.HTML + '/common/';
	URLS.LOGIN = URLS.CONTENT.HTML + '/common/login.html';
	URLS.LOGIN_MODAL = URLS.CONTENT.HTML + '/common/login_modal.html';

	URLS.CONTROL_SIDEBAR = URLS.CONTENT.HTML + '/page/control_sidebar.html';
	URLS.HEADER = URLS.CONTENT.HTML + '/page/header.html';
	URLS.HEADER_SIDEBAR = URLS.CONTENT.HTML + '/page/header_sidebar.html';
	//URLS.REMEMBER_ME = HOST_ROOT + '/page/remember_me.html';
	URLS.COMMUNITY_DIALOG = URLS.CONTENT.HTML + '/page/community_modal.html';

	URLS.FORGET_PASSWORD = URLS.CONTENT.HTML + '/common/forget_password.html';
	URLS.RESET_PASSWORD = URLS.CONTENT.HTML + '/common/reset_password.html';

	URLS.CONTENT.PAGE = {};
	URLS.CONTENT.PAGE.ROOT = URLS.CONTENT.ROOT + '/html';
	URLS.CONTENT.PAGE.PUBLIC = URLS.CONTENT.PAGE.ROOT + '/common';
	URLS.CONTENT.PAGE.PRIVATE = URLS.CONTENT.PAGE.ROOT + '/page';

	URLS.FLOOR_INDEX = URLS.CONTENT.PAGE.PRIVATE + '/index_floor.html';
	
	URLS.CONTENT.DEVICE = {};
	URLS.CONTENT.DEVICE.GATEWAY = URLS.CONTENT.PAGE.PRIVATE + '/gateway.html';
	URLS.CONTENT.DEVICE.CONTROLLER = URLS.CONTENT.PAGE.PRIVATE + '/controller.html';
	URLS.CONTENT.DEVICE.SMART_POWER_METER = URLS.CONTENT.PAGE.PRIVATE + '/smart_power_meter.html';
	URLS.CONTENT.DEVICE.POWER_METER = URLS.CONTENT.PAGE.PRIVATE + '/power_meter.html';
	URLS.CONTENT.DEVICE.CARD_READER = URLS.CONTENT.PAGE.PRIVATE + '/card_reader.html';
	URLS.CONTENT.DEVICE.CHARGE_POINT = URLS.CONTENT.PAGE.PRIVATE + '/charge_point.html';

	URLS.AUTHENTICATE = {};
	URLS.AUTHENTICATE.ROOT = URLS.ROOT + "/authenticate";
	//URLS.AUTHENTICATE.REQUIRE = URLS.AUTHENTICATE.ROOT + '/require';
	URLS.AUTHENTICATE.LOGIN = URLS.AUTHENTICATE.ROOT + '/login';
	URLS.AUTHENTICATE.LOGIN_APP = URLS.AUTHENTICATE.ROOT + '/loginapp';
	URLS.AUTHENTICATE.LOGOUT = URLS.AUTHENTICATE.ROOT + '/logout';
	//URLS.AUTHENTICATE.LOGOUT = URLS.LOGIN;
	URLS.AUTHENTICATE.CHECK = URLS.AUTHENTICATE.ROOT + '/check';
	URLS.AUTHENTICATE.UNLOCK = URLS.AUTHENTICATE.ROOT + '/unlock';
	URLS.AUTHENTICATE.TICKET = URLS.AUTHENTICATE.ROOT + '/ticket';
	//URLS.AUTHENTICATE.EMAIL = URLS.AUTHENTICATE.ROOT + '/email';
	URLS.AUTHENTICATE.CAPTCHA = URLS.AUTHENTICATE.ROOT + '/captcha';
	URLS.AUTHENTICATE.PASSWORD = {};
	URLS.AUTHENTICATE.PASSWORD.ROOT = URLS.AUTHENTICATE.ROOT + '/password';
	URLS.AUTHENTICATE.PASSWORD.CHECK = URLS.AUTHENTICATE.PASSWORD.ROOT + '/check';
	URLS.AUTHENTICATE.PASSWORD.FORGET = URLS.AUTHENTICATE.PASSWORD.ROOT + '/forget';
	URLS.AUTHENTICATE.PASSWORD.RESET = URLS.AUTHENTICATE.PASSWORD.ROOT + '/reset';
	URLS.AUTHENTICATE.PASSWORD.RESET_SAVE = URLS.AUTHENTICATE.PASSWORD.RESET + '/save';

	URLS.SETTING = buildCommonPath("/setting")
	URLS.SETTING.APPLICATION_CONFIG = URLS.SETTING.ROOT + "/config/application";
	URLS.SETTING.COMMUNITY_CONFIG = URLS.SETTING.ROOT + "/config/community/";
	URLS.SETTING.LIST_BY_APPLICATION = URLS.SETTING.LIST + "/application";
	URLS.SETTING.LIST_BY_ORGANIZATION = URLS.SETTING.LIST + "/organization/";
	URLS.SETTING.LIST_BY_COMMUNITY = URLS.SETTING.LIST + "/community/";
	URLS.SETTING.SAVE_APPLICATION = URLS.SETTING.SAVE + "/application";
	URLS.SETTING.SAVE_ORGANIZATION = URLS.SETTING.SAVE + "/organization";
	URLS.SETTING.SAVE_COMMUNITY = URLS.SETTING.SAVE + "/community";
	
	URLS.USER = buildCommonPath("/user");
	URLS.USER.GET = URLS.USER.ROOT + "/get/"
	//URLS.USER.UPDATE_PERSONAL = URLS.USER.ROOT + "/update_personal"
	URLS.USER.SAVE_GARAGE = URLS.USER.SAVE + "/garage"
	URLS.USER.SAVE_PERSONAL = URLS.USER.SAVE + "/personal"
	URLS.USER.LIST_BY_GARAGE = URLS.USER.LIST + "/garage/";
	URLS.USER.LIST_BY_CUSTOMER = URLS.USER.LIST + "/customer/";
	URLS.USER.LIST_BY_COMMUNITY_CUSTOMER = URLS.USER.LIST + "/community/customer";
	URLS.USER.LIST_BY_ORGANIZATION = URLS.USER.LIST + "/organization/";
	URLS.USER.CHECK_LOGIN_ID = URLS.USER.ROOT + "/check/login_id"
	
	URLS.USER_REGISTRATION = buildCommonPath("/user/registration");
	URLS.USER_REGISTRATION.LIST_BY_USER = URLS.USER_REGISTRATION.LIST + "/user/";
	URLS.USER_REGISTRATION.COUNT_BY_USER = URLS.USER_REGISTRATION.COUNT + "/user/";
	URLS.USER_REGISTRATION.SAVE_GARAGE_AND_PARKING_CARD = URLS.USER_REGISTRATION.SAVE + "/garage_and_parking_card";
	
	URLS.ROLE = buildCommonPath("/role");
	URLS.ROLE.LIST_EFFECTIVE = URLS.ROLE.LIST + '/effective';
	
	URLS.COUNTRY = {};
	URLS.COUNTRY.ROOT = HOST_ROOT + "/country";
	URLS.COUNTRY.EFFECTIVE = URLS.COUNTRY.ROOT + "/list/effective";

	URLS.CODE_GROUP = buildCommonPath("/code_group");
	
	URLS.CODE = buildCommonPath("/code");
	URLS.CODE.HELPER = URLS.CODE.ROOT + "/helper";
	URLS.CODE.LIST = {};
	URLS.CODE.LIST.ROOT = URLS.CODE.ROOT + "/list"
	
	URLS.CODE.LIST.COMMON_STATUS = URLS.CODE.LIST.ROOT + "/common_status";
	URLS.CODE.LIST.USER_TYPE = URLS.CODE.LIST.ROOT + "/user_type";
	URLS.CODE.LIST.PARKING_GARAGE_TYPE = URLS.CODE.LIST.ROOT + "/parking_garage_type";
	URLS.CODE.LIST.POWER_TYPE = URLS.CODE.LIST.ROOT + "/power_type";
	URLS.CODE.LIST.POWER_CONNECTOR_TYPE = URLS.CODE.LIST.ROOT + "/power_connector_type";
	URLS.CODE.LIST.SERVICE_ITEM_CATEGORY = URLS.CODE.LIST.ROOT + "/service_item_category";

	URLS.CODE.LIST.SERVICE_STATUS = URLS.CODE.LIST.ROOT + "/service_status";
	URLS.CODE.LIST.SERVICE_ITEM_STATUS = URLS.CODE.LIST.ROOT + "/service_item_status";
	URLS.CODE.LIST.RECHARGE_STATUS = URLS.CODE.LIST.ROOT + "/recharge_status";
	URLS.CODE.LIST.PARKING_SERVICE_TYPE = URLS.CODE.LIST.ROOT + "/parking_service_type";
	URLS.CODE.LIST.CHARGE_TYPE = URLS.CODE.LIST.ROOT + "/charge_type";
	URLS.CODE.LIST.CHARGE_STATUS = URLS.CODE.LIST.ROOT + "/charge_status";
	URLS.CODE.LIST.CONTACT_TYPE = URLS.CODE.LIST.ROOT + "/contact_type";
	URLS.CODE.LIST.NOTIFY_METHOD = URLS.CODE.LIST.ROOT + "/notify_method";
	URLS.CODE.LIST.APPROVE_ACTION = URLS.CODE.LIST.ROOT + "/approve_action";
	URLS.CODE.LIST.PARKING_GARAGE_CATEGORY = URLS.CODE.LIST.ROOT + "/parking_garage_category";
	URLS.CODE.LIST.PARKING_GARAGE_MODEL = URLS.CODE.LIST.ROOT + "/parking_garage_model";
	URLS.CODE.LIST.ELEVATOR_TYPE = URLS.CODE.LIST.ROOT + "/parking_garage_elevator_type";
	URLS.CODE.LIST.DOOR_TYPE = URLS.CODE.LIST.ROOT + "/parking_garage_door_type";
	URLS.CODE.LIST.OPTION = URLS.CODE.LIST.ROOT + "/parking_garage_option";
	URLS.CODE.LIST.BLACKLIST_REASON = URLS.CODE.LIST.ROOT + "/blacklist_reason";
	//URLS.CODE.LIST.RESERVATION_SERVICE_TYPE = URLS.CODE.LIST.ROOT + "/reservation_service_type";
	URLS.CODE.LIST.RESERVATION_STATUS = URLS.CODE.LIST.ROOT + "/reservation_status";
	URLS.CODE.LIST.MAINTENANCE_SERVICE_TYPE = URLS.CODE.LIST.ROOT + "/maintenance_service_type";
	URLS.CODE.LIST.FAULT_CAUSE = URLS.CODE.LIST.ROOT + "/fault_cause";
	URLS.CODE.LIST.POWER_TYPE = URLS.CODE.LIST.ROOT + "/power_type";
	URLS.CODE.LIST.POWER_CONNECTOR_TYPE = URLS.CODE.LIST.ROOT + "/power_connector_type";
	URLS.CODE.LIST.GARAGE_ONWERSHIP = URLS.CODE.LIST.ROOT + "/garage_ownership";
	URLS.CODE.LIST.CHARGING_PILE_TYPE = URLS.CODE.LIST.ROOT + "/charging_pile_type";
	URLS.CODE.LIST.REGISTRATION_STATUS = URLS.CODE.LIST.ROOT + "/registration_status";
	URLS.CODE.LIST.SETTING_STATUS = URLS.CODE.LIST.ROOT + "/setting_status";
	URLS.CODE.LIST.PAYMENT_METHOD = URLS.CODE.LIST.ROOT + "/payment_method";
	URLS.CODE.LIST.DEVICE_CATEGORY = URLS.CODE.LIST.ROOT + "/device_category";
	URLS.CODE.LIST.ACCOUNT_TYPE = URLS.CODE.LIST.ROOT + "/account_type";
	URLS.CODE.LIST.POWER_PHASE = URLS.CODE.LIST.ROOT + "/power_phase";

	URLS.CODE.LIST.PEAK_TIME_TYPE = URLS.CODE.LIST.ROOT + "/peak_time_type";
	URLS.CODE.LIST.PARK_INOUT = URLS.CODE.LIST.ROOT + "/park_inout";
	URLS.CODE.LIST.COMPLETE_PARKING_CHECK = URLS.CODE.LIST.ROOT + "/complete_parking_check";
	
	URLS.CODE.LIST.NOTIFICATION_STATUS = URLS.CODE.LIST.ROOT + "/notification_status";
	URLS.CODE.LIST.CHARGING_STATUS = URLS.CODE.LIST.ROOT + "/charging_status";
	URLS.CODE.LIST.CONNECTION_STATUS = URLS.CODE.LIST.ROOT + "/connection_status";
	URLS.CODE.LIST.POWER_MODE = URLS.CODE.LIST.ROOT + "/power_mode";

	URLS.ORGANIZATION = buildCommonPath("/organization");
	URLS.ORGANIZATION.FAMILY = URLS.ORGANIZATION.ROOT + "/family/";
	URLS.ORGANIZATION.CHECK_NO = URLS.ORGANIZATION.CHECK + "/no";

	URLS.ORGANIZATION.UPLOAD = {};
	URLS.ORGANIZATION.UPLOAD.ROOT = URLS.ORGANIZATION.ROOT + '/upload';
	URLS.ORGANIZATION.UPLOAD.LOGO = URLS.ORGANIZATION.UPLOAD.ROOT + '/logo';
	URLS.ORGANIZATION.UPLOAD.FILE = URLS.ORGANIZATION.UPLOAD.ROOT + '/file';
	URLS.ORGANIZATION.UPLOAD.IMAGE = URLS.ORGANIZATION.UPLOAD.ROOT + '/image';
	URLS.ORGANIZATION.DELETE_LOGO = URLS.ORGANIZATION.DELETE + "/logo/";
	URLS.ORGANIZATION.DELETE_IMAGE = URLS.ORGANIZATION.DELETE + "/image/";

	URLS.CUSTOMER = buildCommonPath("/customer");
	URLS.CUSTOMER.LIST_BY_COMMUNITY = URLS.CUSTOMER.LIST + "/community/";
	URLS.CUSTOMER.LIST_BY_PARKING_GARAGE = URLS.CUSTOMER.LIST + "/parking_garage/";
	URLS.CUSTOMER.CHECK_NO = URLS.CUSTOMER.CHECK + "/no";
	URLS.CUSTOMER.LIST_ADDRESS_BY_COMMUNITY = URLS.CUSTOMER.LIST + "/address/";

	URLS.VENDER = buildCommonPath("/vender");
	URLS.VENDER.CHECK_NO = URLS.VENDER.CHECK + "/no";
	URLS.VENDER.LIST_BY_CRITERIA = URLS.VENDER.LIST + "/criteria";
	
	URLS.MENU = buildCommonPath("/menu");
	URLS.MENU.MANAGEMENT_TREE = URLS.MENU.ROOT + "/tree/management";
	URLS.MENU.CLIENT_TREE = URLS.MENU.ROOT + "/tree/client";

	URLS.CONTACT = buildCommonPath("/contact");
	URLS.CONTACT.LIST_BY_CONSTRUCTION_COMPANY = URLS.CONTACT.LIST + "/construction_company/";
	URLS.CONTACT.LIST_BY_COMMUNITY = URLS.CONTACT.LIST + "/community/";
	URLS.CONTACT.LIST_BY_ORGANIZATION = URLS.CONTACT.LIST + "/organization/";

	URLS.SERVICE_ITEM = buildCommonPath("/service_item");

	URLS.SERVICE_RECORD = buildCommonPath("/service_record");

	URLS.ACTION = buildCommonPath("/action");

	URLS.CONSTRUCTION_COMPANY = buildCommonPath("/construction_company");

	URLS.COMMUNITY = buildCommonPath("/community")
	URLS.COMMUNITY.LIST_BY_ORGANIZATION = URLS.COMMUNITY.LIST + "/organization/";
	URLS.COMMUNITY.LIST_BY_CONSTRUCTION_COMPANY = URLS.COMMUNITY.LIST + "/construction_company/";
	URLS.COMMUNITY.LIST_BY_USER = URLS.COMMUNITY.LIST + "/user/";
	URLS.COMMUNITY.CHECK_NO = URLS.COMMUNITY.CHECK + "/no";
	
	URLS.COMMUNITY.UPLOAD = {};
	URLS.COMMUNITY.UPLOAD.ROOT = URLS.COMMUNITY.ROOT + '/upload';
	URLS.COMMUNITY.UPLOAD.LOGO = URLS.COMMUNITY.UPLOAD.ROOT + '/logo';
	URLS.COMMUNITY.UPLOAD.FILE = URLS.COMMUNITY.UPLOAD.ROOT + '/file';
	
	URLS.PARKING_GARAGE = buildCommonPath("/parking_garage");
	URLS.PARKING_GARAGE.LIST_BY_COMMUNITY = URLS.PARKING_GARAGE.LIST + "/community/";
	URLS.PARKING_GARAGE.CHECK_NO = URLS.PARKING_GARAGE.CHECK + "/no";
	URLS.PARKING_GARAGE.LIST_BY_CUSTOMER = URLS.PARKING_GARAGE.LIST + "/customer/";

	URLS.GARAGE = buildCommonPath("/garage");
	URLS.GARAGE.LIST_BY_PARKING_GARAGE = URLS.GARAGE.LIST + "/parking_garage/";
	URLS.GARAGE.LIST_BY_CUSTOMER = URLS.GARAGE.LIST + "/customer/";
	URLS.GARAGE.LIST_BY_USER = URLS.GARAGE.LIST + "/user/";
	URLS.GARAGE.CHECK_NO = URLS.GARAGE.CHECK + "/no";
	//URLS.GARAGE.LIST_BY_COMMUNITY_AND_USER = URLS.GARAGE.LIST + "/community/{0}/user/{1}";
	URLS.GARAGE.LIST_BY_COMMUNITY_AND_CUSTOMER_AND_USER = URLS.GARAGE.LIST + "/community/{0}/customer/{1}/user/{2}";
	URLS.GARAGE.LIST_CHARGE_POINT_STATE_BY_PARKING_GARAGE = URLS.GARAGE.LIST + "/parking_garage/charge_point_state/";
	URLS.GARAGE.LIST_FLOOR_BY_PARKING_GARAGE = URLS.GARAGE.LIST + "/parking_garage/floor/";

	URLS.GARAGE.COUNT_CHARGING_STATUS_BY_PARKING_GARAGE = URLS.GARAGE.COUNT + "/parking_garage/charging_status";
	
	URLS.GARAGE.SAVE_GARAGE = URLS.GARAGE.SAVE + "/garage";
	URLS.GARAGE.SAVE_PARKING_CARD = URLS.GARAGE.SAVE + "/parking_card";
	URLS.GARAGE.SAVE_USER = URLS.GARAGE.SAVE + "/user";

	URLS.PARKING_CARD = buildCommonPath("/parking_card");
	URLS.PARKING_CARD.CHECK_NO = URLS.PARKING_CARD.CHECK + "/no";
	URLS.PARKING_CARD.LIST_BY_GARAGE = URLS.PARKING_CARD.LIST + "/garage/";
	URLS.PARKING_CARD.LIST_BY_CUSTOMER = URLS.PARKING_CARD.LIST + "/customer/";
	URLS.PARKING_CARD.LIST_BY_USER = URLS.PARKING_CARD.LIST + "/user/";
	//URLS.PARKING_CARD.LIST_BY_COMMUNITY_AND_USER = URLS.PARKING_CARD.LIST + "/community/{0}/user/{1}";
	URLS.PARKING_CARD.LIST_BY_COMMUNITY_AND_CUSTOMER_AND_USER = URLS.PARKING_CARD.LIST + "/community/{0}/customer/{1}/user/{2}";

	URLS.CHARGING_PILE_MODEL = buildCommonPath("/charging_pile_model");
	URLS.CHARGING_PILE_MODEL.CHECK_NO = URLS.CHARGING_PILE_MODEL.CHECK + "/no";

	URLS.CHARGING_PILE = buildCommonPath("/charging_pile");
	URLS.CHARGING_PILE.CHECK_NO = URLS.CHARGING_PILE.CHECK + "/no";

	URLS.TRANSMITTER = buildCommonPath("/transmitter");
	URLS.TRANSMITTER.LIST_BY_COMMUNITY = URLS.TRANSMITTER.LIST + "/community/";
	URLS.TRANSMITTER.CHECK_NO = URLS.TRANSMITTER.CHECK + "/no";

	URLS.CHARGING_PRICE = buildCommonPath("/charging_price");
	URLS.CHARGING_PRICE.ITEM = {};
	URLS.CHARGING_PRICE.ITEM.ROOT = URLS.CHARGING_PRICE.ROOT + "/item";
	URLS.CHARGING_PRICE.ITEM.SAVE = URLS.CHARGING_PRICE.ITEM.ROOT + "/save";
	URLS.CHARGING_PRICE.ITEM.DELETE = URLS.CHARGING_PRICE.ITEM.ROOT + "/delete";

	URLS.WORK_ORDER = {};
	URLS.WORK_ORDER.ROOT = HOST_ROOT + "/workorder";

	URLS.METER_RECORD = buildCommonPath("/meter_record");
	URLS.METER_RECORD.QUERY_PARKING = URLS.METER_RECORD.QUERY + "/parking";
	URLS.METER_RECORD.QUERY_CHARGING = URLS.METER_RECORD.QUERY + "/charging";
	URLS.METER_RECORD.STATISTICS_BY_HOUR = URLS.METER_RECORD.ROOT + "/statistics/parking_garage/hour";
	URLS.METER_RECORD.STATISTICS_BY_LATEST = URLS.METER_RECORD.ROOT + "/statistics/parking_garage/latest";
	URLS.METER_RECORD.STATISTICS_BY_STATUS = URLS.METER_RECORD.ROOT + "/statistics/parking_garage/status";
	URLS.METER_RECORD.STATISTICS_BY_DATES = URLS.METER_RECORD.ROOT + "/statistics/parking_garage/dates";

	URLS.NOTIFICATION = buildCommonPath("/notification");
	URLS.NOTIFICATION.SEND_TEST = URLS.NOTIFICATION.ROOT + "/send/test";
	URLS.NOTIFICATION.COUNT_READING = URLS.NOTIFICATION.ROOT + "/count/reading/";
	URLS.NOTIFICATION.LIST_UNNOTIFIED = URLS.NOTIFICATION.LIST + "/unnotified";
	URLS.NOTIFICATION.UPDATE_NOTIFIED = URLS.NOTIFICATION.ROOT + "/update/notified";
	URLS.NOTIFICATION.UPDATE_READED = URLS.NOTIFICATION.ROOT + "/update/readed";

	URLS.ENTITY = {};
	URLS.ENTITY.ROOT = HOST_ROOT + "/entity";
	URLS.ENTITY.LIST = URLS.ENTITY.ROOT + "/list";

	URLS.USER_RECORD = {};
	URLS.USER_RECORD.ROOT = HOST_ROOT + "/user_record";
	URLS.USER_RECORD.LIST = URLS.USER_RECORD.ROOT + "/list";

	URLS.RECHARGE = buildCommonPath("/recharge")

	URLS.CHARGE = buildCommonPath("/charge")
	URLS.CHARGE.LIST_DETAIL = URLS.CHARGE.LIST + "/detail/";
	URLS.CHARGE.CALCULATE = URLS.CHARGE.ROOT + "/calculate";

	URLS.BILL = buildCommonPath("/bill")

	URLS.APPROVE_RECORD = {};
	URLS.APPROVE_RECORD.ROOT = HOST_ROOT + "/approve_record";
	URLS.APPROVE_RECORD.LIST = URLS.APPROVE_RECORD.ROOT + "/list";
	URLS.APPROVE_RECORD.APPROVING = URLS.APPROVE_RECORD.ROOT + "/approving";
	URLS.APPROVE_RECORD.HISTORY = URLS.APPROVE_RECORD.ROOT + "/history";

	URLS.CITY = buildCommonPath("/city")

	URLS.DISTRICT = buildCommonPath("/district");
	URLS.DISTRICT.LIST_BY_CITY = URLS.DISTRICT.LIST + "/city/";

	URLS.SERVICE_TEAM = buildCommonPath("/service_team");
	URLS.SERVICE_TEAM.LIST_BY_ORGANIZATION = URLS.SERVICE_TEAM.LIST + "/organization/";

	URLS.BLACKLIST = buildCommonPath("/blacklist");

	URLS.RESERVATION = buildCommonPath("/reservation");

	URLS.DEVICE = buildCommonPath("/device")
	URLS.DEVICE.CHECK_NO = URLS.DEVICE.CHECK + "/no";
	URLS.DEVICE.LIST_BY_CRITERIA = URLS.DEVICE.LIST + "/criteria";
	URLS.DEVICE.CONTROLLER_BY_PARKING_GARAGE = URLS.DEVICE.ROOT + "/controller/parking_garage/";
	URLS.DEVICE.GATEWAY_BY_PARKING_GARAGE = URLS.DEVICE.ROOT + "/gateway/parking_garage/";

	URLS.ACCOUNT_BALANCE = buildCommonPath("/account_balance")

	URLS.REGISTRATION = buildCommonPath("/registration");
	URLS.REGISTRATION.LIST_BY_COMMUNITY = URLS.REGISTRATION.LIST + "/community/";
	URLS.REGISTRATION.LIST_BY_CUSTOMER = URLS.REGISTRATION.LIST + "/customer/";
	URLS.REGISTRATION.SAVE_USER = URLS.REGISTRATION.SAVE + "/user";
	URLS.REGISTRATION.LIST_CONFIRM = URLS.REGISTRATION.LIST + "/confirm";
	URLS.REGISTRATION.SAVE_CONFIRM = URLS.REGISTRATION.SAVE + "/confirm";

	URLS.ACCOUNT = buildCommonPath("/account");

	URLS.CALENDAR = buildCommonPath("/calendar");
	URLS.CALENDAR.DEFAULT = URLS.CALENDAR.ROOT + "/default";
	URLS.CALENDAR.NEW_YEAR = URLS.CALENDAR.ROOT + "/new/year";
	URLS.CALENDAR.LIST_ORGANIZATION_YEAR = URLS.CALENDAR.LIST + "/organization/year";
	URLS.CALENDAR.SAVE_ORGANIZATION_YEAR = URLS.CALENDAR.SAVE + "/organization/year";
	URLS.CALENDAR.ROOT_ORGANIZATION_YEAR = URLS.CALENDAR.LIST + "/organization/root/year";
	
	URLS.CLIENT = {};
	URLS.CLIENT.LOGIN = URLS.CONTENT.HTML + '/common/login_client.html';
	URLS.CLIENT.HOME = URLS.CONTENT.HTML + '/page/reserve_record_client.html';
	URLS.CLIENT.RESERVE = URLS.CONTENT.HTML + '/page/reserve_client.html';
	URLS.CLIENT.RESERVE_RECORD = URLS.CONTENT.HTML + '/page/reserve_record_client.html';
	URLS.CLIENT.PARKING_RECORD = URLS.CONTENT.HTML + '/page/parking_record_client.html';
	URLS.CLIENT.CHARGING_RECORD = URLS.CONTENT.HTML + '/page/charging_record_client.html';
	URLS.CLIENT.CHARGE_RECORD = URLS.CONTENT.HTML + '/page/charge_record_client.html';
	URLS.CLIENT.USER = URLS.CONTENT.HTML + '/page/user_client.html';
	URLS.CLIENT.NOTIFICATION = URLS.CONTENT.HTML + '/page/notification_client.html';

	URLS.API = {};
	URLS.API.ROOT = URLS.ROOT + "/api";
	URLS.API.CONTROLLER_DATE_TIME = URLS.API.ROOT + "/controller/date_time";
	URLS.API.CONTROLLER_FIRMWARE_VERSION = URLS.API.ROOT + "/controller/firmware_version";
	URLS.API.CONTROLLER_FIXED_PRICE = URLS.API.ROOT + "/controller/fixed_price";
	URLS.API.CONTROLLER_TOTALIZER = URLS.API.ROOT + "/controller/totalizer";
	URLS.API.CONTROLLER_MAX_POWER = URLS.API.ROOT + "/controller/max_power";
	URLS.API.CONTROLLER_MAX_CONSUMER = URLS.API.ROOT + "/controller/max_consumer";
	URLS.API.CONTROLLER_CHARGABLE_BALANCE = URLS.API.ROOT + "/controller/chargable_balance";
	URLS.API.CONTROLLER_SCREEN_SLEEP = URLS.API.ROOT + "/controller/screen_sleep";
	URLS.API.CONTROLLER_STOP_CHARGING_CONDITION = URLS.API.ROOT + "/controller/stop_charging_condition";
	URLS.API.CONTROLLER_POWER_VOLTAGE_CURRENT = URLS.API.ROOT + "/controller/power_voltage_current";
	URLS.API.CONTROLLER_CHARGE_POINT_BALANCE = URLS.API.ROOT + "/controller/charge_point_balance";
	URLS.API.CONTROLLER_HOLIDAY = URLS.API.ROOT + "/controller/holiday";
	URLS.API.CONTROLLER_MAKEUP_DAY = URLS.API.ROOT + "/controller/makeup_day";
	URLS.API.CONTROLLER_CARD_READER = URLS.API.ROOT + "/controller/card_reader";

	URLS.PACKET = {};
	URLS.PACKET.ROOT = URLS.ROOT + "/packet";
	URLS.PACKET.TRANSACTION_SEQUENCE = URLS.PACKET.ROOT + "/transaction/sequence";

}

setUrls();
